name: client
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  file_picker: ^8.0.3
  flutter:
    sdk: flutter
  flutter_dropzone: ^4.0.0
  geolocator: ^11.0.0
  http: ^1.2.1
  image_picker: ^1.1.1
  intl: ^0.19.0
  js: ^0.7.1
  localstorage: ^5.0.0
  openapi_generator_annotations: ^5.0.2
  permission_handler: ^11.3.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  openapi_generator: ^5.0.2

flutter:
  uses-material-design: true
