name: client
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  animated_flip_counter: ^0.3.4
  file_picker: ^8.0.3
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.2.1
  flutter_local_notifications: ^17.1.2
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.6
  form_builder_validators: ^10.0.1
  geolocator: ^12.0.0
  http: ^1.2.1
  image: ^4.2.0
  image_compression_flutter: ^1.0.4
  image_picker: ^1.1.1
  intl: ^0.19.0
  js: ^0.7.1
  json_theme: ^6.5.0+1
  localstorage: ^5.0.0
  openapi_generator_annotations: ^5.0.2
  permission_handler: ^11.3.1
  preload_page_view: ^0.2.0
  provider: ^6.1.2
  screenshot: ^3.0.0
  simple_shadow: ^0.3.1
  timeago: ^3.6.1
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  openapi_generator: ^5.0.2

flutter:
  uses-material-design: true
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand/Quicksand-VariableFont_wght.ttf
